In [501]:
import pandas as pd
import matplotlib
import seaborn

Import Cleaned dataset

In [502]:
pd.set_option('display.max_columns', None)

#Read Car List dataframe and show maximum columns
 
df_CarList = pd.read_csv("vehicles_dataset.csv")
df_CarList.info(max_cols=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          906 non-null    object
 1   make          906 non-null    object
 2   model         906 non-null    object
 3   year          906 non-null    int64
 4   price         904 non-null    float64
 5   cylinders     906 non-null    object
 6   transmission  906 non-null    object
 7   trim          906 non-null    object
 8   body          906 non-null    object
 9   drivetrain    906 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 70.9+ KB

In [503]:
#Making sure it grabs data for 2024 vehicles only
df_CarList = df_CarList[df_CarList['year'] == 2024]
df_CarList.reset_index(drop=True, inplace=True)

Find missing values

In [504]:
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

<font size="4">We have 252 rows of missing values. Lets clean this up by removing uneccessary columns and remove rows with NaN values

In [505]:
#df_CarList.to_csv('vehicles_dataset.csv', index=False)

#Saves cleaned data to a new file
#df_CarList.drop(columns=["description","fuel","type","engine","interior_color","exterior_color","mileage","doors"], inplace=False)
df_CarList.drop(columns=["name"], inplace=False)

df_CarList.drop_duplicates()

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
0,2024 Jeep Wagoneer Series II,Jeep,Wagoneer,2024,74600.0,6.0,8-Speed Automatic,Series II,SUV,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2024,50170.0,6.0,8-Speed Automatic,Laredo,SUV,Four-wheel Drive
2,2024 GMC Yukon XL Denali,GMC,Yukon XL,2024,96410.0,8.0,Automatic,Denali,SUV,Four-wheel Drive
3,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive
4,2024 Nissan Murano Platinum,Nissan,Murano,2024,46000.0,6.0,Automatic CVT,Platinum,SUV,All-wheel Drive
...,...,...,...,...,...,...,...,...,...,...
900,2024 RAM 2500 Tradesman,RAM,2500,2024,69315.0,6.0,Automatic,Tradesman,Pickup Truck,Four-wheel Drive
901,2024 Mercedes-Benz Sprinter 2500 Standard Roof,Mercedes-Benz,Sprinter 2500,2024,59037.0,4.0,9-Speed Automatic,Standard Roof,Cargo Van,Rear-wheel Drive
903,2024 Jeep Wagoneer Base,Jeep,Wagoneer,2024,69085.0,6.0,8-Speed Automatic,Base,SUV,Four-wheel Drive
904,2024 Nissan Murano SV Intelligent AWD,Nissan,Murano,2024,43495.0,6.0,Automatic,SV Intelligent AWD,SUV,All-wheel Drive
905,2024 Chevrolet Silverado 2500 WT,Chevrolet,Silverado 2500,2024,48995.0,8.0,Automatic,WT,Pickup Truck,Rear-wheel Drive

In [506]:
df_CarList.isnull().sum()

name            0
make            0
model           0
year            0
price           2
cylinders       0
transmission    0
trim            0
body            0
drivetrain      0
dtype: int64

In [507]:
#Find missing values again which resulted in 130 this time
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

In [508]:
#Replacing NaN vaules in cyclinder with 'Eletric' for the Electric Vehicles
df_CarList['cylinders']= df_CarList['cylinders'].fillna("Electric")

#Filling missing values in transmiddion column
df_CarList['transmission']=df_CarList['transmission'].fillna("Automatic")

#Adding SUV to NaNs in the column 'body'
df_CarList['body']=df_CarList['body'].fillna("SUV")

#Finding avg for missing prices and filling the missing price value
df_CarList['price'] = df_CarList['price'].fillna(df_CarList.groupby('model')['price'].transform('mean'))
df_CarList[df_CarList.isnull().any(axis=1)]

#Recheck missing values
df_CarList[df_CarList.isnull().any(axis=1)]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain
614,2024 Mercedes-Benz GLE 350 Base 4MATIC,Mercedes-Benz,GLE 350,2024,NaN,4.0,9-Speed Automatic,Base 4MATIC,SUV,All-wheel Drive
728,2024 BMW 530 i,BMW,530,2024,NaN,4.0,8-Speed Automatic,i,Sedan,Rear-wheel Drive

In [509]:
#Recheck price column for missing values
df_CarList['price'] = df_CarList['price'].fillna(df_CarList.groupby('make')['price'].transform('mean'))
df_CarList[df_CarList.isnull().any(axis=1)]

Empty DataFrame
Columns: [name, make, model, year, price, cylinders, transmission, trim, body, drivetrain]
Index: []

<font size="6">Dataset #1 Cleaned!

In [510]:
df_rcl = pd.read_csv("RCL_FROM_2020_2024.csv")

pd.set_option('display.max_columns', None)

#Read Car List dataframe and show maximum columns
df_rcl.info(max_cols=20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215506 entries, 0 to 215505
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   NHTSA ID       215506 non-null  object
 1   DOCUMENT NAME  215506 non-null  object
 2   MAKE           215506 non-null  object
 3   MODEL          215506 non-null  object
 4   MODEL YEAR     215506 non-null  int64
 5   SUMMARY        215505 non-null  object
dtypes: int64(1), object(5)
memory usage: 9.9+ MB

<font size = 4> Renaming columns to match other dataset before join

In [511]:
df_rcl.rename(columns={'MODEL YEAR': 'year'}, inplace=True)
df_rcl.rename(columns={'MAKE': 'make'}, inplace=True)
df_rcl.rename(columns={'MODEL': 'model'}, inplace=True)
df_rcl.rename(columns={'SUMMARY': 'summary'}, inplace=True)
print(df_rcl.info)
df_rcl.head(20)

<bound method DataFrame.info of        NHTSA ID          DOCUMENT NAME      make          model  year  \
0        20E003  RCRIT-20E003-7585.pdf   CUMMINS  POWERDRIVE EV  9999
1        20E003   RCMN-20E003-7457.pdf   CUMMINS  POWERDRIVE EV  9999
2        20E004  RMISC-20E004-5516.pdf  FREEDMAN     BENCH SEAT  9999
3        20E004  RMISC-20E004-6489.pdf  FREEDMAN     BENCH SEAT  9999
4        20E004  RMISC-20E004-6489.pdf  FREEDMAN  FOLDAWAY SEAT  9999
...         ...                    ...       ...            ...   ...
215501   24V970  RCRIT-24V970-4111.pdf    INDIAN    SCOUT SIXTY  2025
215502   24V970  RMISC-24V970-1551.pdf    INDIAN    SCOUT SIXTY  2025
215503   24V970   RCMN-24V970-7276.pdf    INDIAN    SCOUT SIXTY  2025
215504   24V970   RCMN-24V970-1200.pdf    INDIAN    SCOUT SIXTY  2025
215505   24V970   RCMN-24V970-8406.pdf    INDIAN    SCOUT SIXTY  2025

                                                  summary
0       This document contains the field action campai...
1       This document is an OEM notice to inform the a...
2                      product recall notification letter
3               Final copy - customer notification letter
4               Final copy - customer notification letter
...                                                   ...
215501  This is a communication to dealers regarding N...
215502  This is a communication to consumers regarding...
215503  This is a communication to Dealers regarding N...
215504  This is a communication to dealers regarding N...
215505  This is a communication to dealers regarding N...

[215506 rows x 6 columns]>

,NHTSA ID,DOCUMENT NAME,make,model,year,summary
0,20E003,RCRIT-20E003-7585.pdf,CUMMINS,POWERDRIVE EV,9999,This document contains the field action campai...
1,20E003,RCMN-20E003-7457.pdf,CUMMINS,POWERDRIVE EV,9999,This document is an OEM notice to inform the a...
2,20E004,RMISC-20E004-5516.pdf,FREEDMAN,BENCH SEAT,9999,product recall notification letter
3,20E004,RMISC-20E004-6489.pdf,FREEDMAN,BENCH SEAT,9999,Final copy - customer notification letter
4,20E004,RMISC-20E004-6489.pdf,FREEDMAN,FOLDAWAY SEAT,9999,Final copy - customer notification letter
5,20E004,RMISC-20E004-5516.pdf,FREEDMAN,FOLDAWAY SEAT,9999,product recall notification letter
6,20E009,RCMN-20E009-4111.pdf,TOW KING,12K TOP WIND JACK,9999,"NOTICE TO DEALERS OF DEFECT, REMEDY INSTRUCTIO..."
7,20E013,RCMN-20E013-2751.pdf,BMW,BRAKE FLUID RES. COVER,9999,Manufacturer Notice to Dealers
8,20E013,RIONL-20E013-7354.pdf,BMW,BRAKE FLUID RES. COVER,9999,Interim Owner Notification Letter
9,20E013,RCMN-20E013-6045.pdf,BMW,BRAKE FLUID RES. COVER,9999,Manufacturer Notices to Dealers
10,20E013,RCONL-20E013-7739.pdf,BMW,BRAKE FLUID RES. COVER,9999,Owner Notification Letter
11,20E013,RCMN-20E013-5539.pdf,BMW,BRAKE FLUID RES. COVER,9999,Manufacturer Notice to Dealers
12,20E013,RCMN-20E013-2751.pdf,BMW,R 1250 GS,2019,Manufacturer Notice to Dealers
13,20E013,RCONL-20E013-7739.pdf,BMW,R 1250 GS,2019,Owner Notification Letter
14,20E013,RCMN-20E013-5539.pdf,BMW,R 1250 GS,2019,Manufacturer Notice to Dealers
15,20E013,RCMN-20E013-6045.pdf,BMW,R 1250 GS,2019,Manufacturer Notices to Dealers
16,20E013,RIONL-20E013-7354.pdf,BMW,R 1250 GS,2019,Interim Owner Notification Letter
17,20E013,RCMN-20E013-6045.pdf,BMW,R 1250 GS,2020,Manufacturer Notices to Dealers
18,20E013,RIONL-20E013-7354.pdf,BMW,R 1250 GS,2020,Interim Owner Notification Letter
19,20E013,RCONL-20E013-7739.pdf,BMW,R 1250 GS,2020,Owner Notification Letter

<font size="4">Grabbing data for only 2024 vehicles, and checking for missing values.

In [512]:
df_rcl = df_rcl[df_rcl["year"] == 2024]
df_rcl.reset_index(drop=True, inplace=True)
df_rcl.isnull().sum()

NHTSA ID         0
DOCUMENT NAME    0
make             0
model            0
year             0
summary          0
dtype: int64

<font size="4">Check and remove duplicate lines.

In [513]:
df_rcl.drop_duplicates()
df_rcl[df_rcl.isnull().any(axis=1)]
print(df_rcl.info)

<bound method DataFrame.info of      NHTSA ID          DOCUMENT NAME                  make     model  year  \
0      22V909  RCONL-22V909-2556.pdf                IC BUS      CESB  2024
1      22V909  RCRIT-22V909-1126.pdf                IC BUS      CESB  2024
2      23V065  RCONL-23V065-7947.pdf                IC BUS      CESB  2024
3      23V065  RCRIT-23V065-4342.pdf                IC BUS      CESB  2024
4      23V087  RCONL-23V087-5040.pdf              KENWORTH      T280  2024
...       ...                    ...                   ...       ...   ...
9458   24V966  RCONL-24V966-6482.pdf  STORYTELLER OVERLAND    MYSTIC  2024
9459   24V966   RCMN-24V966-1472.pdf  STORYTELLER OVERLAND   STEALTH  2024
9460   24V966  RCONL-24V966-6482.pdf  STORYTELLER OVERLAND   STEALTH  2024
9461   24V968  RCONL-24V968-6389.pdf  STORYTELLER OVERLAND  GXV HILT  2024
9462   24V968   RCMN-24V968-0243.pdf  STORYTELLER OVERLAND  GXV HILT  2024

                                                summary
0     22527; 02/06/2023; IC Bus; CE - 2022 & 2023; R...
1     22527; 02/01/2023; IC bus; CE - 2022 & 2023; R...
2     23501; 04/03/2023; IC Bus; 2022 thru 2024 CE, ...
3     23501; 04/03/2023; IC Bus; 2022 thru 2024 CE, ...
4     Attached letter is the FINAL customer notifica...
...                                                 ...
9458  This is our final Owner Notification Letter, t...
9459  This our Dealer Final Notification. This docum...
9460  This is our final Owner Notification Letter, t...
9461  This is our Final 577 Customer Notification; t...
9462  This is our final copy of our Dealer Notificat...

[9463 rows x 6 columns]>

<font size="4">Remove Semi Trucks, Trailer, Three-wheelers etc. and all other vechicles not intended for daily drivers. This data is for the purpose of regular non commercial drivers.

In [514]:
non_vehicles = ("MACK", "KENWORTH", "TOW KING", "MCI", "CUMMINS", "LIGHTING EMOTORS", "SPARTAN FIRE", "AGILITY FUEL SYSTEMS", "MOPAR", "RUGGED LINERS", "ALTEC", "KEYSTONE", "THOMAS BUILT BUSES",
                "CARRIER TRANSICOLD", "PITTSBURGH AUTOMOTIVE", "FREEDMAN", "KZRN", "PJ TRAILERS", "LODE KING", "NEXUS", "TIFFIN", "WINNEBAGO", "NIKOLA", "VINFAST", "HOLIDAY RAMBLER",
                "JAYCO", "HEARTLAND", "PRATT INTERNATIONAL", "CFMOTO", "XOS", "AIRSTREAM", "INDIAN", "WESTERN STAR", "CAN-AM", "MAINTAINER", "NOVA BUS", "THOR MOTOR COACH", "FREIGHTLINER",
                "PETERBILT", "UTILITY TRAILER", "ARCIMOTO", "NEW FLYER", "KIDRON", "LION", "TICO", "SUPER PRODUCTS", "HINO", "AUTOCAR", "TRIPPLE E", "TRIPLE R", "KAWASAKI", "SCHWARZE", 
                "KZRZ", "TRAIL KING", "CRUISER RV", "TEREX", "TEREX ADVANCED", "INTERNATIONAL", "IC BUS", "FCCC", "VERMEER", "FOREST RIVER BUS", "HUSQVARNA", "KTM", "ZERO", "VAN HOOL",
                "FLEETWOOD", "BRUAN AMBULANCE", "FEILD VAN", "STORYTELLER OVERLAND", "KME", "SAFARI CONDO", "CUMMINS POWER GENERATION", "MITSUBISHI FUSO", "POLESTAR",
                "AKRON BRASS COMPANY", "TEKONSHA", "DANA", "DOMETIC", "DANA", "LIPPERT", "CODE 3", "AC DELCO", "NAPA", "SAAB", "DRAW-TITE", "TIMPTE", "STARCRAFT BUS", "ENDERA", "MICRO BIRD",
                "BRINKLEY RV", "COACHMEN", "FOREST RIVER", "DELCO TRAILERS", "DOOSAN PORTABLE POWER", "MOTIV", "TAXA", "DOOSAN", "LIVEWIRE", "ROSENBAUER", "CRUISER", "MORBARK", 
                "KENTUCY TRAILER KY", "HARLEY-DAVIDSON", "ROYAL ENFIELD", "CATALINA", "DYNAMAX", "EAST TO WEST", "ATC", "NEWMAR", "AURORA", "VANCRAFT", "OLIVER TRAVEL TRAILERS", "PIERCE", "VIKING TRAVEL TRAILERS")

df_rcl = df_rcl[~df_rcl['make'].isin(non_vehicles)]
df_rcl.reset_index(drop=True, inplace=True)

In [515]:

df_rcl[df_rcl.isnull().any(axis=1)]

#df_rcl.drop_duplicates("SUMMARY")
df_rcl.drop(columns= "DOCUMENT NAME",)

print(df_rcl.info)
df_rcl.head(20)

<bound method DataFrame.info of      NHTSA ID          DOCUMENT NAME   make model  year  \
0      23V173  RCRIT-23V173-6991.pdf  VOLVO   VHD  2024
1      23V173  RCRIT-23V173-4613.pdf  VOLVO   VHD  2024
2      23V173  RCRIT-23V173-3354.pdf  VOLVO   VHD  2024
3      23V173   RCMN-23V173-3463.pdf  VOLVO   VHD  2024
4      23V173  RCRIT-23V173-7160.pdf  VOLVO   VHD  2024
...       ...                    ...    ...   ...   ...
6593   24V962   RCMN-24V962-3806.pdf    KIA   EV9  2024
6594   24V962  RCRIT-24V962-7747.pdf    KIA   EV9  2024
6595   24V962  RCONL-24V962-1772.pdf    KIA   EV9  2024
6596   24V962   RCMN-24V962-3299.pdf    KIA   EV9  2024
6597   24V962   RCMN-24V962-3393.pdf    KIA   EV9  2024

                                                summary
0     On certain trucks, the hub covers on the drive...
1     On certain trucks, the hub covers on the drive...
2     Volvo has determined that some hub covers, lac...
3     On certain trucks, the hub covers on the drive...
4     Volvo has determined that some hub covers, lac...
...                                                 ...
6593  The Q&A contains questions and answers regardi...
6594  The Technical Service Bulletin (TSB) lists spe...
6595  Owner Letter notifies the customer of the safe...
6596  The Dealer Parts & Service Manager letter is t...
6597  The Dealer Principal letter is to notify the d...

[6598 rows x 6 columns]>

,NHTSA ID,DOCUMENT NAME,make,model,year,summary
0,23V173,RCRIT-23V173-6991.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
1,23V173,RCRIT-23V173-4613.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
2,23V173,RCRIT-23V173-3354.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
3,23V173,RCMN-23V173-3463.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
4,23V173,RCRIT-23V173-7160.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
5,23V173,RCONL-23V173-9318.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
6,23V173,RCONL-23V173-9318.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
7,23V173,RCMN-23V173-3463.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
8,23V173,RCRIT-23V173-7160.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
9,23V173,RCRIT-23V173-6991.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
10,23V173,RCRIT-23V173-4613.pdf,VOLVO,VNL,2024,"On certain trucks, the hub covers on the drive..."
11,23V173,RCRIT-23V173-3354.pdf,VOLVO,VNL,2024,"Volvo has determined that some hub covers, lac..."
12,23V173,RCRIT-23V173-4613.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
13,23V173,RCONL-23V173-9318.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
14,23V173,RCMN-23V173-3463.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
15,23V173,RCRIT-23V173-7160.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
16,23V173,RCRIT-23V173-6991.pdf,VOLVO,VNR,2024,"On certain trucks, the hub covers on the drive..."
17,23V173,RCRIT-23V173-3354.pdf,VOLVO,VNR,2024,"Volvo has determined that some hub covers, lac..."
18,23V280,RCRIT-23V280-5344.pdf,VOLVO,VNR,2024,Coolant Lines in battery pack may not be prope...
19,23V280,RCRIT-23V280-5658.pdf,VOLVO,VNR,2024,Coolant Lines in battery pack may not be prope...

In [516]:
print(df_rcl['make'].unique())

['VOLVO' 'BMW' 'FORETRAVEL' 'JAGUAR' 'GREAT DANE' 'LEXUS' 'HYUNDAI'
 'PORSCHE' 'CHINOOK' 'KIA' 'HIGHLAND RIDGE' 'CHEVROLET' 'GMC' 'LAKOTA'
 'SUBARU' 'ISUZU' 'JEEP' 'TRIUMPH' 'VOLKSWAGEN' 'WILSON' 'ALFA ROMEO'
 'DODGE' 'FORD' 'RAM' 'CADILLAC' 'BRIGHTDROP' 'FERRARI' 'HONDA' 'NISSAN'
 'MERCEDES-BENZ' 'BUICK' 'TOYOTA' 'TRIPLE E RV' 'LAND ROVER' 'MCLAREN'
 'INFINITI' 'CUSHMAN' 'LAMBORGHINI' 'INEOS' 'AUDI' 'SUZUKI' 'ROLLS-ROYCE'
 'LUCID' 'ACURA' 'MERCEDES-MAYBACH' 'ELKHART' 'ENTEGRA' 'CHRYSLER'
 'GENESIS' 'READING TRUCK EQUIPMENT' 'DUTCHMEN' 'BIG TEX' 'CHAMPION'
 'ELDORADO' 'GLAVAL BUS' 'CROSSROADS' 'MINI' 'RIVIAN' 'MOBILITY TRANS'
 'CLIPPER TOWABLE' 'VIKING TOWABLE' 'BRAUNABILITY' 'LINCOLN' 'FIAT'
 'MASERATI' 'TRIPLE E' 'ESCAPE' 'KENTUCKY TRAILER' 'ASTON MARTIN' 'MAZDA'
 'PAGANI' 'RICH SPECIALITY TRAILERS']

<font size="6">Dataset #2 Cleaned!

<font size = "4"> Now combine both datasets to join into one large dataset

In [520]:
df_CarList.head()
df_rcl.head()

,NHTSA ID,DOCUMENT NAME,make,model,year,summary
0,23V173,RCRIT-23V173-6991.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
1,23V173,RCRIT-23V173-4613.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
2,23V173,RCRIT-23V173-3354.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."
3,23V173,RCMN-23V173-3463.pdf,VOLVO,VHD,2024,"On certain trucks, the hub covers on the drive..."
4,23V173,RCRIT-23V173-7160.pdf,VOLVO,VHD,2024,"Volvo has determined that some hub covers, lac..."

In [ ]:
#merge
merged_df = pd.merge(df_CarList, df_rcl, on=['make', 'model', 'year'], how='inner')
print(merged_df['make'].unique())

#concatnated
#merged_df = pd.concat([df_CarList, df_rcl], ignore_index=True)
print(merged_df)
merged_df.head(29)
#print(merged_df['make'].unique())
#print(merged_df['make'].unique().sum)

['RAM' 'BMW' 'INFINITI']
                         name make model  year    price cylinders  \
0       2024 RAM 3500 Laramie  RAM  3500  2024  81663.0       6.0
1       2024 RAM 3500 Laramie  RAM  3500  2024  81663.0       6.0
2       2024 RAM 3500 Laramie  RAM  3500  2024  81663.0       6.0
3       2024 RAM 3500 Laramie  RAM  3500  2024  81663.0       6.0
4       2024 RAM 3500 Laramie  RAM  3500  2024  81663.0       6.0
...                       ...  ...   ...   ...      ...       ...
4189  2024 RAM 2500 Tradesman  RAM  2500  2024  69315.0       6.0
4190  2024 RAM 2500 Tradesman  RAM  2500  2024  69315.0       6.0
4191  2024 RAM 2500 Tradesman  RAM  2500  2024  69315.0       6.0
4192  2024 RAM 2500 Tradesman  RAM  2500  2024  69315.0       6.0
4193  2024 RAM 2500 Tradesman  RAM  2500  2024  69315.0       6.0

           transmission       trim          body        drivetrain NHTSA ID  \
0     6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive   23V799
1     6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive   23V799
2     6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive   23V799
3     6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive   23V799
4     6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive   23V799
...                 ...        ...           ...               ...      ...
4189          Automatic  Tradesman  Pickup Truck  Four-wheel Drive   24V199
4190          Automatic  Tradesman  Pickup Truck  Four-wheel Drive   24V199
4191          Automatic  Tradesman  Pickup Truck  Four-wheel Drive   24V199
4192          Automatic  Tradesman  Pickup Truck  Four-wheel Drive   24V199
4193          Automatic  Tradesman  Pickup Truck  Four-wheel Drive   24V199

              DOCUMENT NAME                                            summary
0     RMISC-23V799-2706.pdf  Email Blast sent to certain customers regardin...
1     RCRIT-23V799-9972.pdf  Dealer Instructions regarding certain \n\n2023...
2      RCRN-23V799-2968.pdf  Renotification Letter regarding certain 2023-2...
3      RCRN-23V799-5072.pdf       Renotification regarding FCA US campaign B2A
4     RCRIT-23V799-2407.pdf  Revised Dealer Instructions regarding certain:...
...                     ...                                                ...
4189   RCMN-24V199-7011.pdf  NSRAC-Interim Owner Letter Combo regarding FCA...
4190   RCMN-24V199-6500.pdf  Revised NSRAC regarding certain 2023 Jeep Glad...
4191   RCMN-24V199-1054.pdf  Revised NSRAC regarding certain 2023 Model Yea...
4192   RCMN-24V199-1713.pdf  Revised NSRAC regarding certain 2023 Jeep Gran...
4193   RCMN-24V199-2816.pdf  NSRAC regarding certain 2023 Model Year Chrysl...

[4194 rows x 13 columns]

,name,make,model,year,price,cylinders,transmission,trim,body,drivetrain,NHTSA ID,DOCUMENT NAME,summary
0,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RMISC-23V799-2706.pdf,Email Blast sent to certain customers regardin...
1,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRIT-23V799-9972.pdf,Dealer Instructions regarding certain \n\n2023...
2,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRN-23V799-2968.pdf,Renotification Letter regarding certain 2023-2...
3,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRN-23V799-5072.pdf,Renotification regarding FCA US campaign B2A
4,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRIT-23V799-2407.pdf,Revised Dealer Instructions regarding certain:...
5,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRIT-23V799-1624.pdf,Revised Dealer Combo regarding certain 2023-20...
6,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCMN-23V799-2066.pdf,NSRAC regarding certain 2024 Model Year RAM 35...
7,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCMN-23V799-4358.pdf,Revised NSRAC regarding certain 2023 Model Yea...
8,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCMN-23V799-6612.pdf,NSRAC regarding certain 2023 Model Year Ram 35...
9,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCONL-23V799-4565.pdf,Final Owner Letter regarding certain 2023-2024...
10,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCONL-23V799-7211.pdf,Final Owner Letter regarding certain 2024 mode...
11,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRIT-23V799-0888.pdf,Revised Dealer Combo regarding certain 2023-20...
12,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRN-23V799-7583.pdf,Renotification regarding FCA US campaign D5A
13,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRN-23V799-9490.pdf,Renotification Letter regarding certain 2024 m...
14,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,23V799,RCRIT-23V799-7862.pdf,Dealer Instructions regarding certain: \n\n202...
15,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-5767.pdf,NSRAC-Final Owner Letter Combo regarding certa...
16,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-6471.pdf,NSRAC regarding certain 2023 Jeep Gladiator an...
17,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-6500.pdf,Revised NSRAC regarding certain 2023 Jeep Glad...
18,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-7011.pdf,NSRAC-Interim Owner Letter Combo regarding FCA...
19,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-7321.pdf,NSRAC-Final Owner Letter Combo regarding certa...
20,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-8050.pdf,NSRAC regarding certain 2023 Jeep Grand Cherok...
21,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-8308.pdf,Combined NSRAC-Final Owner Letter regarding ce...
22,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-8437.pdf,Revised NSRAC regarding certain 2023 Ram 1500 ...
23,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-8760.pdf,NSRAC regarding certain 2023 and 2024 Ram 1500...
24,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-9851.pdf,Revised NSRAC regarding certain 2023 and 2024 ...
25,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCMN-24V199-9889.pdf,NSRAC regarding certain 2023 Ram 1500 Classic ...
26,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCONL-24V199-0486.pdf,Final Owner Letter regarding certain 2023 Jeep...
27,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCONL-24V199-0967.pdf,Final Owner Letter regarding certain 2023 Ram ...
28,2024 RAM 3500 Laramie,RAM,3500,2024,81663.0,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,24V199,RCONL-24V199-2157.pdf,Completed Owner Letter regarding 2023 Jeep Gra...

In [519]:
#.............print(merged_df.info)
#merged_df.drop_duplicates
#merged_df.head(20)
merged_df['recall'] = merged_df.groupby(['make', 'model', 'year'])['NHTSA ID'].transform('nunique')

print(merged_df.info)
merged_df.head()

KeyError: 'make'

In [480]:
finshed_df = merged_df.drop(columns=['summary', 'DOCUMENT NAME', 'NHTSA ID','price'])
finshed_df = finshed_df.drop_duplicates()
print(finshed_df.info)
finshed_df.head()

<bound method DataFrame.info of                                                 name      make model  year  \
0                              2024 RAM 3500 Laramie       RAM  3500  2024
57                           2024 RAM 3500 Tradesman       RAM  3500  2024
171                          2024 RAM 2500 Tradesman       RAM  2500  2024
290                            2024 BMW X7 xDrive40i       BMW    X7  2024
444                          2024 RAM 3500 Tradesman       RAM  3500  2024
501      2024 RAM 3500 Tradesman Crew Cab 4x4 8' Box       RAM  3500  2024
558                            2024 RAM 3500 Laramie       RAM  3500  2024
672                          2024 INFINITI QX50 LUXE  INFINITI  QX50  2024
677        2024 RAM 3500 Laramie Crew Cab 4x4 8' Box       RAM  3500  2024
791      2024 RAM 3500 Tradesman/SLT/Laramie/Limited       RAM  3500  2024
848      2024 RAM 3500 Laramie Mega Cab 4x4 6'4' Box       RAM  3500  2024
962                           2024 RAM 2500 Big Horn       RAM  2500  2024
1024                           2024 RAM 2500 Laramie       RAM  2500  2024
1205                          2024 RAM 3500 Big Horn       RAM  3500  2024
1319                          2024 RAM 2500 Longhorn       RAM  2500  2024
1386                          2024 RAM 3500 Big Horn       RAM  3500  2024
1500                         2024 RAM 3500 Tradesman       RAM  3500  2024
1614                                2024 BMW X7 M60i       BMW    X7  2024
1711                         2024 RAM 2500 Tradesman       RAM  2500  2024
2006                         2024 RAM 2500 Tradesman       RAM  2500  2024
2068                       2024 RAM 2500 Power Wagon       RAM  2500  2024
2358      2024 RAM 2500 Tradesman 4x4 Crew Cab 8 Box       RAM  2500  2024
2534                        2024 INFINITI QX50 SPORT  INFINITI  QX50  2024
2653                          2024 RAM 3500 Big Horn       RAM  3500  2024
3950                           2024 BMW X3 sDrive30i       BMW    X3  2024
3956  2024 RAM 2500 Tradesman Regular Cab 4x4 8' Box       RAM  2500  2024

     cylinders             transmission  \
0          6.0        6-Speed Automatic
57         6.0                Automatic
171        8.0                Automatic
290        6.0        8-Speed Automatic
444        6.0        6-Speed Automatic
501        6.0                Automatic
558        6.0                Automatic
672        4.0                 Variable
677        6.0                Automatic
791        6.0                Automatic
848        6.0  Aisin 6-Speed Automatic
962        8.0        8-Speed Automatic
1024       6.0        6-Speed Automatic
1205       6.0        6-Speed Automatic
1319       6.0                Automatic
1386       6.0                Automatic
1500       8.0        8-Speed Automatic
1614       8.0        8-Speed Automatic
1711       8.0        8-Speed Automatic
2006       6.0                Automatic
2068       6.0                Automatic
2358       6.0              6-Speed A/T
2534       4.0          (CVT) CONT VAR.
2653       6.0  Aisin 6-Speed Automatic
3950       4.0  8-Speed Automatic Sport
3956       8.0                Automatic

                                       trim          body         drivetrain  \
0                                   Laramie  Pickup Truck   Four-wheel Drive
57                                Tradesman  Pickup Truck   Four-wheel Drive
171                               Tradesman  Pickup Truck   Four-wheel Drive
290                               xDrive40i           SUV    All-wheel Drive
444                               Tradesman  Pickup Truck   Four-wheel Drive
501       Tradesman Crew Cab 4x4 8&#39; Box  Pickup Truck   Four-wheel Drive
558                                 Laramie  Pickup Truck   Four-wheel Drive
672                                    LUXE           SUV  Front-wheel Drive
677         Laramie Crew Cab 4x4 8&#39; Box  Pickup Truck   Four-wheel Drive
791           Tradesman/SLT/Laramie/Limited  Pickup Truck   Four-wheel Drive
848   Laramie Mega Cab 4x4 6&#39;4&#39; Box  Pickup Truck   Four-wheel Drive
962                                Big Horn  Pickup Truck   Four-wheel Drive
1024                                Laramie  Pickup Truck   Four-wheel Drive
1205                               Big Horn  Pickup Truck   Four-wheel Drive
1319                               Longhorn  Pickup Truck   Four-wheel Drive
1386                               Big Horn  Pickup Truck   Four-wheel Drive
1500                              Tradesman  Pickup Truck   Four-wheel Drive
1614                                   M60i           SUV    All-wheel Drive
1711                              Tradesman  Pickup Truck   Four-wheel Drive
2006                              Tradesman  Pickup Truck   Four-wheel Drive
2068                            Power Wagon  Pickup Truck   Four-wheel Drive
2358           Tradesman 4x4 Crew Cab 8 Box  Pickup Truck   Four-wheel Drive
2534                                  SPORT           SUV  Front-wheel Drive
2653                               Big Horn  Pickup Truck   Four-wheel Drive
3950                              sDrive30i           SUV   Rear-wheel Drive
3956   Tradesman Regular Cab 4x4 8&#39; Box  Pickup Truck   Four-wheel Drive

      recall
0          2
57         2
171        3
290        6
444        2
501        2
558        2
672        1
677        2
791        2
848        2
962        3
1024       3
1205       2
1319       3
1386       2
1500       2
1614       6
1711       3
2006       3
2068       3
2358       3
2534       1
2653       2
3950       1
3956       3  >

,name,make,model,year,cylinders,transmission,trim,body,drivetrain,recall
0,2024 RAM 3500 Laramie,RAM,3500,2024,6.0,6-Speed Automatic,Laramie,Pickup Truck,Four-wheel Drive,2
57,2024 RAM 3500 Tradesman,RAM,3500,2024,6.0,Automatic,Tradesman,Pickup Truck,Four-wheel Drive,2
171,2024 RAM 2500 Tradesman,RAM,2500,2024,8.0,Automatic,Tradesman,Pickup Truck,Four-wheel Drive,3
290,2024 BMW X7 xDrive40i,BMW,X7,2024,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,6
444,2024 RAM 3500 Tradesman,RAM,3500,2024,6.0,6-Speed Automatic,Tradesman,Pickup Truck,Four-wheel Drive,2

<font size = "4"> I will establish a final dataset to list the nubmer of recalls instead of having each recall listed with files and case id. This way it will be clearer for users to see and easier to graph. If there are missing values for the "recall" the chart will say none or no recalls.

In [440]:
#df_grouped = merged_df.groupby(['make', 'model', 'year', 'NHTSA ID', 'summary']).agg({
    'DOCUMENT NAME': lambda x: ', '.join(set(x)),
    'price': 'first',
    'cylinders': 'first',
    'transmission': 'first',
    'trim': 'first',
    'body': 'first',
    'drivetrain': 'first'
}).reset_index()

print(df_grouped.info)
df_grouped.head(20)

<bound method DataFrame.info of     make model  year NHTSA ID  \
0    BMW    X3  2024   23V770
1    BMW    X3  2024   23V770
2    BMW    X3  2024   23V770
3    BMW    X3  2024   23V770
4    BMW    X7  2024   23V471
..   ...   ...   ...      ...
146  RAM  3500  2024   24V199
147  RAM  3500  2024   24V199
148  RAM  3500  2024   24V199
149  RAM  3500  2024   24V199
150  RAM  3500  2024   24V199

                                               summary  \
0                      Manufacturer Notices to Dealers
1                               Miscellaneous Document
2                                                  ONL
3                          Remedy Instructions and TSB
4                      Manufacturer Notices to Dealers
..                                                 ...
146  Revised NSRAC regarding certain 2023 Jeep Glad...
147  Revised NSRAC regarding certain 2023 Jeep Gran...
148  Revised NSRAC regarding certain 2023 Model Yea...
149  Revised NSRAC regarding certain 2023 Ram 1500 ...
150  Revised NSRAC regarding certain 2023 and 2024 ...

                                         DOCUMENT NAME    price cylinders  \
0                                 RCMN-23V770-9860.pdf  49395.0       4.0
1                                RMISC-23V770-9903.pdf  49395.0       4.0
2                                RCONL-23V770-4332.pdf  49395.0       4.0
3    RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...  49395.0       4.0
4           RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf  89450.0       6.0
..                                                 ...      ...       ...
146                               RCMN-24V199-6500.pdf  81663.0       6.0
147                               RCMN-24V199-1713.pdf  81663.0       6.0
148                               RCMN-24V199-1054.pdf  81663.0       6.0
149                               RCMN-24V199-8437.pdf  81663.0       6.0
150                               RCMN-24V199-9851.pdf  81663.0       6.0

                transmission       trim          body        drivetrain
0    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
1    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
2    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
3    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
4          8-Speed Automatic  xDrive40i           SUV   All-wheel Drive
..                       ...        ...           ...               ...
146        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
147        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
148        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
149        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
150        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive

[151 rows x 12 columns]>

,make,model,year,NHTSA ID,summary,DOCUMENT NAME,price,cylinders,transmission,trim,body,drivetrain
0,BMW,X3,2024,23V770,Manufacturer Notices to Dealers,RCMN-23V770-9860.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive
1,BMW,X3,2024,23V770,Miscellaneous Document,RMISC-23V770-9903.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive
2,BMW,X3,2024,23V770,ONL,RCONL-23V770-4332.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive
3,BMW,X3,2024,23V770,Remedy Instructions and TSB,"RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...",49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive
4,BMW,X7,2024,23V471,Manufacturer Notices to Dealers,"RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
5,BMW,X7,2024,23V471,Miscellaneous Document,RMISC-23V471-2441.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
6,BMW,X7,2024,23V471,ONL,RCONL-23V471-8036.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
7,BMW,X7,2024,23V471,Remedy Instructions and TSB,"RCRIT-23V471-2226.pdf, RCRIT-23V471-3784.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
8,BMW,X7,2024,23V471,Remedy instructions and TSB,RCRIT-23V471-4416.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
9,BMW,X7,2024,23V622,Manufacturer Notices to Dealers,"RCMN-23V622-0369.pdf, RCMN-23V622-1644.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
10,BMW,X7,2024,23V622,Miscellaneous Document,RMISC-23V622-6314.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
11,BMW,X7,2024,23V622,ONL,RCONL-23V622-2817.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
12,BMW,X7,2024,23V622,Remedy Instructions and TSB,"RCRIT-23V622-8351.pdf, RCRIT-23V622-4775.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
13,BMW,X7,2024,24V104,Interim ONL,"RIONL-24V104-4674.pdf, RIONL-24V104-3114.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
14,BMW,X7,2024,24V104,Manufacturer Notices to Dealers,"RCMN-24V104-3106.pdf, RCMN-24V104-7180.pdf, RC...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
15,BMW,X7,2024,24V104,Manufacturers Notices to Dealers,RCMN-24V104-4450.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
16,BMW,X7,2024,24V104,Miscellaneous Document,"RMISC-24V104-3475.pdf, RMISC-24V104-7238.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
17,BMW,X7,2024,24V104,ONL,"RCONL-24V104-0883.pdf, RCONL-24V104-0500.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
18,BMW,X7,2024,24V104,Remedy Instructions and TSB,"RCRIT-24V104-5800.pdf, RCRIT-24V104-8761.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive
19,BMW,X7,2024,24V138,Manufacturer Notices to Dealers,RCMN-24V138-2772.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive

In [458]:
#Counting total recall amount
df_grouped['recalls'] = df_grouped.groupby(['make', 'model', 'year'])['DOCUMENT NAME'].transform('nunique')
print(df_grouped.info)
df_grouped.head(20)

<bound method DataFrame.info of     make model  year NHTSA ID  \
0    BMW    X3  2024   23V770
1    BMW    X3  2024   23V770
2    BMW    X3  2024   23V770
3    BMW    X3  2024   23V770
4    BMW    X7  2024   23V471
..   ...   ...   ...      ...
146  RAM  3500  2024   24V199
147  RAM  3500  2024   24V199
148  RAM  3500  2024   24V199
149  RAM  3500  2024   24V199
150  RAM  3500  2024   24V199

                                               summary  \
0                      Manufacturer Notices to Dealers
1                               Miscellaneous Document
2                                                  ONL
3                          Remedy Instructions and TSB
4                      Manufacturer Notices to Dealers
..                                                 ...
146  Revised NSRAC regarding certain 2023 Jeep Glad...
147  Revised NSRAC regarding certain 2023 Jeep Gran...
148  Revised NSRAC regarding certain 2023 Model Yea...
149  Revised NSRAC regarding certain 2023 Ram 1500 ...
150  Revised NSRAC regarding certain 2023 and 2024 ...

                                         DOCUMENT NAME    price cylinders  \
0                                 RCMN-23V770-9860.pdf  49395.0       4.0
1                                RMISC-23V770-9903.pdf  49395.0       4.0
2                                RCONL-23V770-4332.pdf  49395.0       4.0
3    RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...  49395.0       4.0
4           RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf  89450.0       6.0
..                                                 ...      ...       ...
146                               RCMN-24V199-6500.pdf  81663.0       6.0
147                               RCMN-24V199-1713.pdf  81663.0       6.0
148                               RCMN-24V199-1054.pdf  81663.0       6.0
149                               RCMN-24V199-8437.pdf  81663.0       6.0
150                               RCMN-24V199-9851.pdf  81663.0       6.0

                transmission       trim          body        drivetrain  \
0    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
1    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
2    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
3    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
4          8-Speed Automatic  xDrive40i           SUV   All-wheel Drive
..                       ...        ...           ...               ...
146        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
147        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
148        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
149        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
150        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive

     recalls
0          4
1          4
2          4
3          4
4         27
..       ...
146       55
147       55
148       55
149       55
150       55

[151 rows x 13 columns]>

,make,model,year,NHTSA ID,summary,DOCUMENT NAME,price,cylinders,transmission,trim,body,drivetrain,recalls
0,BMW,X3,2024,23V770,Manufacturer Notices to Dealers,RCMN-23V770-9860.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
1,BMW,X3,2024,23V770,Miscellaneous Document,RMISC-23V770-9903.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
2,BMW,X3,2024,23V770,ONL,RCONL-23V770-4332.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
3,BMW,X3,2024,23V770,Remedy Instructions and TSB,"RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...",49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
4,BMW,X7,2024,23V471,Manufacturer Notices to Dealers,"RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
5,BMW,X7,2024,23V471,Miscellaneous Document,RMISC-23V471-2441.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
6,BMW,X7,2024,23V471,ONL,RCONL-23V471-8036.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
7,BMW,X7,2024,23V471,Remedy Instructions and TSB,"RCRIT-23V471-2226.pdf, RCRIT-23V471-3784.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
8,BMW,X7,2024,23V471,Remedy instructions and TSB,RCRIT-23V471-4416.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
9,BMW,X7,2024,23V622,Manufacturer Notices to Dealers,"RCMN-23V622-0369.pdf, RCMN-23V622-1644.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
10,BMW,X7,2024,23V622,Miscellaneous Document,RMISC-23V622-6314.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
11,BMW,X7,2024,23V622,ONL,RCONL-23V622-2817.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
12,BMW,X7,2024,23V622,Remedy Instructions and TSB,"RCRIT-23V622-8351.pdf, RCRIT-23V622-4775.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
13,BMW,X7,2024,24V104,Interim ONL,"RIONL-24V104-4674.pdf, RIONL-24V104-3114.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
14,BMW,X7,2024,24V104,Manufacturer Notices to Dealers,"RCMN-24V104-3106.pdf, RCMN-24V104-7180.pdf, RC...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
15,BMW,X7,2024,24V104,Manufacturers Notices to Dealers,RCMN-24V104-4450.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
16,BMW,X7,2024,24V104,Miscellaneous Document,"RMISC-24V104-3475.pdf, RMISC-24V104-7238.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
17,BMW,X7,2024,24V104,ONL,"RCONL-24V104-0883.pdf, RCONL-24V104-0500.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
18,BMW,X7,2024,24V104,Remedy Instructions and TSB,"RCRIT-24V104-5800.pdf, RCRIT-24V104-8761.pdf, ...",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27
19,BMW,X7,2024,24V138,Manufacturer Notices to Dealers,RCMN-24V138-2772.pdf,89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27

<font size = 4> Full Data frame with summary and file location

In [459]:
full_df = df_grouped
print(full_df.info)
full_df.head()

<bound method DataFrame.info of     make model  year NHTSA ID  \
0    BMW    X3  2024   23V770
1    BMW    X3  2024   23V770
2    BMW    X3  2024   23V770
3    BMW    X3  2024   23V770
4    BMW    X7  2024   23V471
..   ...   ...   ...      ...
146  RAM  3500  2024   24V199
147  RAM  3500  2024   24V199
148  RAM  3500  2024   24V199
149  RAM  3500  2024   24V199
150  RAM  3500  2024   24V199

                                               summary  \
0                      Manufacturer Notices to Dealers
1                               Miscellaneous Document
2                                                  ONL
3                          Remedy Instructions and TSB
4                      Manufacturer Notices to Dealers
..                                                 ...
146  Revised NSRAC regarding certain 2023 Jeep Glad...
147  Revised NSRAC regarding certain 2023 Jeep Gran...
148  Revised NSRAC regarding certain 2023 Model Yea...
149  Revised NSRAC regarding certain 2023 Ram 1500 ...
150  Revised NSRAC regarding certain 2023 and 2024 ...

                                         DOCUMENT NAME    price cylinders  \
0                                 RCMN-23V770-9860.pdf  49395.0       4.0
1                                RMISC-23V770-9903.pdf  49395.0       4.0
2                                RCONL-23V770-4332.pdf  49395.0       4.0
3    RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...  49395.0       4.0
4           RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf  89450.0       6.0
..                                                 ...      ...       ...
146                               RCMN-24V199-6500.pdf  81663.0       6.0
147                               RCMN-24V199-1713.pdf  81663.0       6.0
148                               RCMN-24V199-1054.pdf  81663.0       6.0
149                               RCMN-24V199-8437.pdf  81663.0       6.0
150                               RCMN-24V199-9851.pdf  81663.0       6.0

                transmission       trim          body        drivetrain  \
0    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
1    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
2    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
3    8-Speed Automatic Sport  sDrive30i           SUV  Rear-wheel Drive
4          8-Speed Automatic  xDrive40i           SUV   All-wheel Drive
..                       ...        ...           ...               ...
146        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
147        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
148        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
149        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive
150        6-Speed Automatic    Laramie  Pickup Truck  Four-wheel Drive

     recalls
0          4
1          4
2          4
3          4
4         27
..       ...
146       55
147       55
148       55
149       55
150       55

[151 rows x 13 columns]>

,make,model,year,NHTSA ID,summary,DOCUMENT NAME,price,cylinders,transmission,trim,body,drivetrain,recalls
0,BMW,X3,2024,23V770,Manufacturer Notices to Dealers,RCMN-23V770-9860.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
1,BMW,X3,2024,23V770,Miscellaneous Document,RMISC-23V770-9903.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
2,BMW,X3,2024,23V770,ONL,RCONL-23V770-4332.pdf,49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
3,BMW,X3,2024,23V770,Remedy Instructions and TSB,"RCRIT-23V770-0224.pdf, RCRIT-23V770-8566.pdf, ...",49395.0,4.0,8-Speed Automatic Sport,sDrive30i,SUV,Rear-wheel Drive,4
4,BMW,X7,2024,23V471,Manufacturer Notices to Dealers,"RCMN-23V471-6396.pdf, RCMN-23V471-3646.pdf",89450.0,6.0,8-Speed Automatic,xDrive40i,SUV,All-wheel Drive,27

<font size = 4>Finshed Datafram which will make it a bit nicer looking removing Docs., summary, and repetive looking rows

In [471]:
finshed_df = df_grouped.drop(columns=['summary', 'DOCUMENT NAME', 'NHTSA ID'])
finshed_df = finshed_df.drop_duplicates()
print(finshed_df.info)

<bound method DataFrame.info of         make model  year    price cylinders             transmission  \
0        BMW    X3  2024  49395.0       4.0  8-Speed Automatic Sport
4        BMW    X7  2024  89450.0       6.0        8-Speed Automatic
31  INFINITI  QX50  2024  48350.0       4.0                 Variable
36       RAM  2500  2024  58855.0       8.0                Automatic
96       RAM  3500  2024  81663.0       6.0        6-Speed Automatic

         trim          body         drivetrain  recalls
0   sDrive30i           SUV   Rear-wheel Drive        4
4   xDrive40i           SUV    All-wheel Drive       27
31       LUXE           SUV  Front-wheel Drive        5
36  Tradesman  Pickup Truck   Four-wheel Drive       60
96    Laramie  Pickup Truck   Four-wheel Drive       55  >

<font size = "4"> Storing data in SQLite

In [421]:
import sqlite3
import tabulate

<font size = "4"> Create Plots plus Tableau